#!/bin/sh
set -eu

install -o root -g root -m 0755 /home/nate/mechbot-admin /usr/local/sbin/mechbot-admin
printf '%s\n' 'nate ALL=(root) NOPASSWD: /usr/local/sbin/mechbot-admin' > /etc/sudoers.d/mechbot-admin
chmod 0440 /etc/sudoers.d/mechbot-admin
visudo -cf /etc/sudoers.d/mechbot-admin
echo 'MechBot restricted admin helper installed.'
